#!/usr/bin/env python3
import sys
import re

alp = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890,.?/-()'
morse = [
    '.-',
    '-...',
    '-.-.',
    '-..',
    '.',
    '..-.',
    '--.',
    '....',
    '..',
    '.---',
    '-.-',
    '.-..',
    '--',
    '-.',
    '---',
    '.--.',
    '--.-',
    '.-.',
    '...',
    '-',
    '..-',
    '...-',
    '.--',
    '-..-',
    '-.--',
    '--..',
    '.----',
    '..---',
    '...--',
    '....-',
    '.....',
    '-....',
    '--...',
    '---..',
    '----.',
    '-----',
    '--..--',
    '.-.-.-',
    '..--..',
    '-..-.',
    '-....-',
    '-.--.',
    '-.--.-',
]

def encode(message):

    morsecode = dict(zip(alp, morse))
    available_e = set(alp)
    encoded = ''
    for letter in message:
        if letter in available_e:
            encoded += morsecode[letter] + ' '
        elif letter == ' ':
            encoded += letter
        else:
            encoded += '*'

    return encoded

def decode(encoded):
    morsecode = dict(zip(morse, alp))
    available_d = set(morse)
    encoded = encoded.split()
    decoded = ''
    for patt in encoded:
        if patt in available_d:
            decoded += morsecode[patt]
        else:
            decoded += '*'
    return decoded


if __name__ == '__main__':
    args = sys.argv

    if len(args) == 1:
        s = input()
    elif re.match(r'\-\w', args[-1]):
        s = input()
    else:
        s = args[-1]

    s = s.upper()

    if '-d' in args:
        print(decode(s))
    else:
        print(encode(s))
