#!/usr/bin/env python3
import sys
import argparse

alp = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890,.?/-()'
morse = [
    '.-',
    '-...',
    '-.-.',
    '-..',
    '.',
    '..-.',
    '--.',
    '....',
    '..',
    '.---',
    '-.-',
    '.-..',
    '--',
    '-.',
    '---',
    '.--.',
    '--.-',
    '.-.',
    '...',
    '-',
    '..-',
    '...-',
    '.--',
    '-..-',
    '-.--',
    '--..',
    '.----',
    '..---',
    '...--',
    '....-',
    '.....',
    '-....',
    '--...',
    '---..',
    '----.',
    '-----',
    '--..--',
    '.-.-.-',
    '..--..',
    '-..-.',
    '-....-',
    '-.--.',
    '-.--.-',
]

def encode(message):
    morsecode = dict(zip(alp, morse))
    available_e = set(alp)
    encoded = ''
    for letter in message:
        if letter in available_e:
            encoded += morsecode[letter] + ' '
        elif letter == ' ':
            encoded += letter
        else:
            encoded += '*'

    return encoded

def decode(encoded):
    morsecode = dict(zip(morse, alp))
    available_d = set(morse)
    encoded = encoded.split()
    decoded = ''
    for patt in encoded:
        if patt in available_d:
            decoded += morsecode[patt]
        else:
            decoded += '*'
    return decoded


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Encode/Decode morse code')

    parser.add_argument('-d', '--decode', help='decode morse', action='store_true')

    parser.add_argument('infile', nargs='?', type=argparse.FileType('r'), default=sys.stdin)

    args = parser.parse_args()

    s = args.infile.readline().strip().upper()

    if args.decode:
        print(decode(s))
    else:
        print(encode(s))
